export const CHANGE_HOME_PAGE_DATA = 'home/CHANGE_HOME_PAGE_DATA'

export const CHANGE_BANNER_LIST = 'home/CHANGE_BANNER_LIST'

export const CHANGE_RECOMMEND_LIST = 'home/CHANGE_RECOMMEND_LIST'

export const CHANGE_PRIVATE_SONGS_LIST = 'home/CHANGE_PRIVATE_SONGS_LIST'

export const CHANGE_FEATURED_SONGS_LIST = 'home/CHANGE_FEATURED_SONGS_LIST'

export const CHANGE_LEADERBOARD_LIST = 'home/CHANGE_LEADERBOARD_LIST'

export const CHANGE_NEW_ALBUM_LIST = 'home/CHANGE_NEW_ALBUM_LIST'

export const CHANGE_ENTER_LOADING = 'home/CHANGE_ENTER_LOADING'

export const CHANGE_SEARCH_DEFAULT = 'home/CHANGE_SEARCH_DEFAULT'
